export const START_LOGIN = "START_LOGIN_FRONT_DESK";
export const LOGIN_SUCCESS = "FRONT_DESK_LOGIN_SUCCESS";
export const LOGIN_FAIL = "FRONT_DESK_LOGIN_FAIL";
export const START_STAFF_LOGIN = "START_STAFF_LOGIN";
export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAIL = "STAFF_LOGIN_FAIL";
